name: MailTape
markdown: kramdown
pygments: true
permalink: /:categories/:title/
timezone: Europe/Paris

## kramdown config to force interpretation into html block
kramdown:
  parse_block_html: true

## prose.io config
prose:
  rooturl: '_posts'
  siteurl: 'http://MailTape.github.io/'
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'img/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "episode"
      # - name: "author"
      #   field:
      #     element: "text"
      #     label: "Who are you dude ?"
      #     help: "Used for your signature. Please keep the same name for each of your episode to stay consistent."
      #     placeholder: "Write your name"
      #     type: "text"
      - name: "author"
        field:
          element: "select"
          label: "Who are you dude ?"
          placeholder: "Choose your name"
          options:
            - name: "Dimitri"
              value: "Dimitri"
            - name: "Julien"
              value: "Julien"
            - name: "ImaCrea"
              value: "ImaCrea"
            - name: "Ludovic"
              value: "Ludovic"
            - name: "MailTape Crew"
              value: "MailTape Crew"
      - name: "category"
        field:
          element: "text"
          label: "Which episode ?"
          placeholder: "130"
      - name: "guest_name"
        field:
          element: "text"
          label: "Guest name"
          placeholder: "Valentin Stip"
          type: "text"
      - name: "guest_color"
        field:
          element: "select"
          label: "Color of the artist"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "bigTitle_font_ratio"
        field:
          element: "text"
          label: "Big title font ratio"
          help: "Valeur à modifier pour l'ajustement de la taille du grand titre. Plus la valeur est grande plus le titre est petit. Attention à utiliser des . et pas des , pour les valeurs telles que 6.45 par ex."
          value: "6"
      - name: "bigTitle_line_ratio"
        field:
          element: "text"
          label: "Big title line ratio"
          help: "Valeur à modifier pour l'ajustement de la hauteur du grand titre. Fonctionnement similaire au font ratio."
          value: "1"
      - name: "guest_pic"
        field:
          element: "text"
          label: "img guest URL"
          placeholder: "img/...jpg"
          type: "text"
      - name: "track1_link"
        field:
          element: "text"
          label: "Track1 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track2_link"
        field:
          element: "text"
          label: "Track2 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track3_link"
        field:
          element: "text"
          label: "Track3 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track4_link"
        field:
          element: "text"
          label: "Track4 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track5_link"
        field:
          element: "text"
          label: "Track5 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track6_link"
        field:
          element: "text"
          label: "Track6 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track7_link"
        field:
          element: "text"
          label: "Track7 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track1_title"
        field:
          element: "text"
          label: "Track1 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track1_color"
        field:
          element: "select"
          label: "Track1 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track2_title"
        field:
          element: "text"
          label: "Track2 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track2_color"
        field:
          element: "select"
          label: "Track2 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track3_title"
        field:
          element: "text"
          label: "Track3 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track3_color"
        field:
          element: "select"
          label: "Track3 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track4_title"
        field:
          element: "text"
          label: "Track4 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track4_color"
        field:
          element: "select"
          label: "Track4 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track5_title"
        field:
          element: "text"
          label: "Track5 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track5_color"
        field:
          element: "select"
          label: "Track5 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track6_title"
        field:
          element: "text"
          label: "Track6 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track6_color"
        field:
          element: "select"
          label: "Track6 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track7_title"
        field:
          element: "text"
          label: "Track7 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track7_color"
        field:
          element: "select"
          label: "Track7 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "episode_URL"
        field:
          element: "text"
          label: "Episode URL ?"
          placeholder: "http://mailta.pe/129/Valentin-Stip"
          type: "text"
      - name: "episode_FB_Pic"
        field:
          element: "text"
          label: "img FB URL"
          placeholder: "http://mailta.pe/img/fbPics_129.jpg"
          type: "text"
      - name: "musicolor"
        field:
          element: "text"
          label: "img musicolor URL"
          placeholder: "http://mailta.pe/img/musicolors/129.png"
          type: "text"
      - name: "description"
        field:
          element: "textarea"
          label: "Opengraph description"
          help: "Small text inserted with epiode when shared on fb"
          placeholder: "This morning, welcome on Dream Airlines. Our captain, Valentin Stip, will take us off to glowing masses of condensed sound vapor floating in the sky."