name: MailTape
description: We release a playlist co-curated with a surprise guest each Sunday morning. üíé
author: MailTape Crew
markdown: kramdown
pygments: false
highlighter: rouge
permalink: /:categories/:title/
timezone: Europe/Paris
paginate: 12
future: true

include: ['.htaccess','_headers']

## kramdown config to force interpretation into html block
kramdown:
  parse_block_html: true

## prose.io config
prose:
  rooturl: '_posts'
  siteurl: 'https://mailta.pe/'
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'img'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "episode"
      # - name: "author"
      #   field:
      #     element: "text"
      #     label: "Who are you dude ?"
      #     help: "Used for your signature. Please keep the same name for each of your episode to stay consistent."
      #     placeholder: "Write your name"
      #     type: "text"
      - name: "author"
        field:
          element: "select"
          label: "Who are you ?"
          placeholder: "Choose your name"
          options:
            - name: "Ana√Øs G"
              value: "Ana√Øs G"
            - name: "Arthur"
              value: "Arthur"
            - name: "Charlotte"
              value: "Charlotte"
            - name: "Dimitri"
              value: "Dimitri"
            - name: "Jules"
              value: "Jules"
            - name: "Julien"
              value: "Julien"
            - name: "ImaCrea"
              value: "ImaCrea"
            - name: "In√®s"
              value: "In√®s"
            - name: "Laura"
              value: "Laura"
            - name: "Louise"
              value: "Louise"
            - name: "Luc"
              value: "Luc"
            - name: "Ludovic"
              value: "Ludovic"
            - name: "Maxime"
              value: "Maxime"
            - name: "Manon"
              value: "Manon"
            - name: "Marion"
              value: "Marion"
            - name: "Olivier"
              value: "Olivier"
            - name: "PS KY"
              value: "PS KY"
            - name: "Sanjay"
              value: "Sanjay Mistry"
            - name: "Sarah"
              value: "Sarah"
            - name: "MailTape Crew"
              value: "MailTape Crew"
      - name: "illustrator"
        field:
          element: "select"
          label: "Who did the illustration?"
          placeholder: "Choose illustrator"
          options:
            - name: "Anthony"
              value: "Anthony Dujardin"
            - name: "Aoife"
              value: "Aoife Comey"
            - name: "Anais"
              value: "Anais Caura"
            - name: "Celestin"
              value: "Camille C√©lestin"
            - name: "Emilie"
              value: "Emilie Rouge"
            - name: "Isabelle"
              value: "Isabelle Escande"
            - name: "Pierre-Julien"
              value: "Pierre-Julien Fieux"
            - name: "William"
              value: "William Girault"
            - name: "Thibault"
              value: "Thibault Daumain"
            - name: "Julie"
              value: "Julie Wojtczak"
      - name: "writer"
        field:
          element: "select"
          label: "Who wrote the text?"
          placeholder: "Choose writer"
          options:
            - name: "Ana√Øs G"
              value: "Ana√Øs G"
            - name: "Arthur"
              value: "Arthur"
            - name: "Charlotte"
              value: "Charlotte"
            - name: "Daisy"
              value: "Daisy"
            - name: "Dimitri"
              value: "Dimitri"
            - name: "ImaCrea"
              value: "ImaCrea"
            - name: "Jules"
              value: "Jules"
            - name: "In√®s"
              value: "In√®s"
            - name: "Laura"
              value: "Laura"
            - name: "Louise"
              value: "Louise"
            - name: "Luc"
              value: "Luc"
            - name: "Ludovic"
              value: "Ludovic"
            - name: "Maxime"
              value: "Maxime"
            - name: "Manon"
              value: "Manon"
            - name: "Marion"
              value: "Marion"
            - name: "PS KY"
              value: "PS KY"
            - name: "Sanjay"
              value: "Sanjay Mistry"
            - name: "Sarah"
              value: "Sarah"
            - name: "Siddhartha"
              value: "Siddhartha"
      - name: "category"
        field:
          element: "text"
          label: "Which episode ?"
          placeholder: "131"
      - name: "guest_name"
        field:
          element: "text"
          label: "Guest name"
          placeholder: "Valentin Stip"
          type: "text"
      - name: "guest_color"
        field:
          element: "select"
          label: "Color of the artist"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "bigTitle_font_ratio"
        field:
          element: "text"
          label: "Big title font ratio"
          help: "Big title font size adjustement. The bigger the value, the smaller the title. Be careful to use dot and not comma for float numbers."
          value: "6"

      # fini le line ratio suite au passage √† la nouvelle version de flowtype
      # - name: "bigTitle_line_ratio"
      #   field:
      #     element: "text"
      #     label: "Big title line ratio"
      #     help: "Big title height adjustement. Working same as font ratio"
      #     value: "1"
      
      - name: "guestPic"
        field:
          element: "text"
          label: "img guestPic name"
          help: "Once you have uploaded the guestPic, write here name of the image. Convention : guestPic131.jpg"
          placeholder: "guestPic131.jpg"
          type: "text"
      - name: "track1_link"
        field:
          element: "text"
          label: "Track1 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track2_link"
        field:
          element: "text"
          label: "Track2 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track3_link"
        field:
          element: "text"
          label: "Track3 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track4_link"
        field:
          element: "text"
          label: "Track4 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track5_link"
        field:
          element: "text"
          label: "Track5 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track6_link"
        field:
          element: "text"
          label: "Track6 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track7_link"
        field:
          element: "text"
          label: "Track7 link"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track1_title"
        field:
          element: "text"
          label: "Track1 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track1_color"
        field:
          element: "select"
          label: "Track1 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track2_title"
        field:
          element: "text"
          label: "Track2 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track2_color"
        field:
          element: "select"
          label: "Track2 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track3_title"
        field:
          element: "text"
          label: "Track3 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track3_color"
        field:
          element: "select"
          label: "Track3 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track4_title"
        field:
          element: "text"
          label: "Track4 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track4_color"
        field:
          element: "select"
          label: "Track4 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track5_title"
        field:
          element: "text"
          label: "Track5 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track5_color"
        field:
          element: "select"
          label: "Track5 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track6_title"
        field:
          element: "text"
          label: "Track6 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track6_color"
        field:
          element: "select"
          label: "Track6 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track7_title"
        field:
          element: "text"
          label: "Track7 title"
          placeholder: "Valentin Stip - Correlation"
          type: "text"

      - name: "track7_color"
        field:
          element: "select"
          label: "Track7 color"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "episode_URL"
        field:
          element: "text"
          label: "Episode URL ?"
          help: "Warning : be careful with caps and don't forget '/' at end!"
          placeholder: "http://mailta.pe/129/Valentin-Stip/"
          type: "text"
      - name: "image"
        field:
          element: "text"
          label: "fbPic file"
          help: "(NEW!) Once fbPic uploaded, write here its FULL PATH. Convention : https://mailta.pe/img/fbPic131.png"
          placeholder: "https://mailta.pe/img/fbPic131.png"
          type: "text"
      - name: "musiColor"
        field:
          element: "text"
          label: "musiColor file"
          help: "Once you have uploaded the MusiColor, write here name of the image. Convention : musiColor131.png"
          placeholder: "musiColor131.png"
          type: "text"
      - name: "description"
        field:
          element: "text"
          label: "Opengraph description"
          help: "Copy Paste your intro here, without links please"
          placeholder: "This morning, welcome on Dream Airlines. Our captain, Valentin Stip, will take us off to glowing masses of condensed sound vapor floating in the sky."
          type: "text"

# add rss feed
gems:
  - jekyll-feed
url: https://mailta.pe
repository: MailTape/MailTape.github.io
